// Code generated by "gobatis -type=User"; DO NOT EDIT.
package mapper

import "log"
import "gobatis/model"

type UserMapper struct {
}

func (this *UserMapper) GetAll() []model.User {
	rows, err := db.Query("select id,account from user")
	defer rows.Close()
	results := make([]model.User, 0)
	if err != nil {
		log.Println(err.Error())
		return results
	}
	for rows.Next() {
		temp := model.User{}

		rows.Scan(&temp.Id, &temp.Account)
		results = append(results, temp)
	}
	return results
}
